dataset:
  name: video_games
  review_url: https://mcauleylab.ucsd.edu/public_datasets/data/amazon_2023/raw/review_categories/Video_Games.jsonl.gz
  min_interactions: 5

model:
  vocab_size: null
  max_sequence_length: 50
  model_dim: 64
  num_heads: 4
  num_layers: 4
  dropout: 0.5
  learning_rate: 0.001

training:
  batch_size: 128
  train_steps: 10000
  steps_per_eval: 500
  steps_per_loop: 100
  model_dir: runs/video_games
